name: Docker Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t onxxim-test .

      - name: Test Docker image
        run: |
          docker run --rm onxxim-test echo "Docker build successful!"

      - name: Test generating onnx file - GPT2
        run: |
          docker run --rm onxxim-test python3 /workspace/ONNXim/scripts/generate_transformer_onnx.py --model gpt2

      - name: Test generating onnx file - BERT
        run: |
          docker run --rm onxxim-test python3 /workspace/ONNXim/scripts/generate_transformer_onnx.py --model bert

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
